### PR TITLE
make gem loadable under Rails 3

### PR DESCRIPTION
**Pull request by niklas**
this involved only the addition of one file. Rails 3 looks for a file called like the gem.

### CODE REVIEW

**Comment by niklas** [comment]
This also affects issue #26

**Comment by svenfuchs** [comment]
Hey Niklas, thanks for the pull request. I'm not sure I should apply it though.

As said on Twitter this is the version of globalize which is intended for use with Rails 3: http://github.com/svenfuchs/globalize3

**Comment by tomash** [comment]
what is it for, given globalize3 designed from ground-up to be rails3 compatible?

**Comment by niklas** [comment]
@svenfuch Sorry, I thought you referred to the branch. My fault

**Comment by svenfuchs** [comment]
no worries.

i just have hoped to save you some unnecessary work :(

still ... lemme know if you find problems with globalize3

**Pull request closed without merging**
